// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    'OTPAuthenticatorRegister.NEXT': 'Next',
    'OTPAuthenticatorRegister.BACK': 'Back',
    'OTPAuthenticatorRegister.INTRO': 'Register the {label} to use for authentication.',
    'OTPAuthenticatorRegister.HOW_TO_USE': 'How to use one-time passwords.',
    'OTPAuthenticatorVerify.RESEND': 'Resend code',
    'OTPAuthenticatorVerify.ERROR_FIELD': 'Invalid {field} value',
    'OTPAuthenticatorVerify.VERIFY': 'Use the code that was sent to',
    'OTPAuthenticatorVerify.ENTER_CODE': 'Enter {length}-digit code'
});
}