// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "TwilioRegister.NEXT": "Next",
    "TwilioRegister.BACK": "Back",
    "TwilioRegister.INTRO": "Register the mobile phone number to use for authentication.",
    "TwilioRegister.HOW_TO_USE": "How to use authenticator app.",
    "TwilioVerify.NEXT": "Next",
    "TwilioVerify.HOW_TO_USE": "How to use authenticator app.",
    "TwilioVerify.VERIFY": "Use the code that was sent to",
    "TwilioVerify.ENTER_CODE": "Enter {length}-digit code",
    "TwilioRegister.PHONE": "Mobile phone",
    "TwilioVerify.RESEND": "Resend code"
});
}