// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "TwilioRegister.NEXT": "Volgende",
    "TwilioRegister.BACK": "Vorige",
    "TwilioRegister.INTRO": "Registreer het mobiele nummer welke je wilt gebruiken voor authenticatie.",
    "TwilioRegister.HOW_TO_USE": "Hoe gebruik je een authenticator app?",
    "TwilioVerify.NEXT": "Volgende",
    "TwilioVerify.HOW_TO_USE": "Hoe gebruik je een authenticator app?",
    "TwilioVerify.VERIFY": "Gebruik de code welke is verstuurd naar",
    "TwilioVerify.ENTER_CODE": "Voor een {length}-cijferige code in",
    "TwilioRegister.PHONE": "Mobiel nummer"
});
}