// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    'OTPAuthenticatorRegister.NEXT': 'Volgende',
    'OTPAuthenticatorRegister.BACK': 'Vorige',
    'OTPAuthenticatorRegister.INTRO': 'Registreer het {label} welke je wilt gebruiken voor authenticatie.',
    'OTPAuthenticatorRegister.HOW_TO_USE': 'Hoe gebruik je een eenmalig wachtwoord?',
    'OTPAuthenticatorVerify.RESEND': 'Verstuur code opnieuw',
    'OTPAuthenticatorVerify.ERROR_FIELD': 'Foutief {field}',
    'OTPAuthenticatorVerify.VERIFY': 'Gebruik de code welke is verstuurd naar',
    'OTPAuthenticatorVerify.ENTER_CODE': 'Voer een {length}-cijferige code in'
});
}