---
Name: OTPAuthenticator
---
# Register the method
SilverStripe\MFA\Service\MethodRegistry:
  methods:
    otp: XD\OTPAuthenticator\Method

# Register the default provider
SilverStripe\Core\Injector\Injector:
  XD\OTPAuthenticator\Providers\SendProvider:
    class: XD\OTPAuthenticator\Providers\EmailProvider
    # class: XD\OTPAuthenticator\Providers\TwilioProvider
    # class: XD\OTPAuthenticator\Providers\SMSToolsProvider

SilverStripe\MFA\Authenticator\LoginHandler:
  extensions:
    - XD\OTPAuthenticator\Extensions\LoginHandlerExtension
SilverStripe\MFA\Controller\AdminRegistrationController:
  extensions:
    - XD\OTPAuthenticator\Extensions\AdminRegistrationControllerExtension
