<?php

declare(strict_types=1);

namespace XD\OTPAuthenticator;

use OTPHP\OTPInterface;
use OTPHP\TOTP;
use RuntimeException;
use SilverStripe\Core\Environment;
use SilverStripe\MFA\Store\StoreInterface;

trait TOTPAware
{
    protected function getCode($store): string
    {
        $totp = $this->getTotp($store);
        $code = $totp->now();
        return $code;
    }

    protected function verify($code, $store): bool
    {
        $totp = $this->getTotp($store);
        return $totp->verify($code);
    }

     /**
     * Gets the encryption key to use from environment variables. This is generated by default on the Common Web
     * Platform, but can be defined as a custom value if required.
     *
     * @return string
     */
    protected function getEncryptionKey(): string
    {
        return (string) Environment::getEnv('SS_MFA_SECRET_KEY');
    }
    

    /**
     * Get an instance of the TOTP handler service. The secret must already be defined and set to the StoreInterface.
     *
     * @param StoreInterface $store
     * @return TOTPInterface
     * @throws RuntimeException
     */
    protected function getTotp(StoreInterface $store): OTPInterface
    {
        $state = $store->getState();
        if (!isset($state['secret'])) {
            throw new RuntimeException('OTP secret is not available in the StoreInterface');
        }

        // configure period, default is 30 sec.
        // for sms/email otp's should be 60 sec ?

        return TOTP::create($state['secret']);
    }
}
